# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'photo-map' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for photo-map
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'SwiftyJSON'
end
